"""
================================================================================
ZK-ML AOT Circuit Compiler Engine
================================================================================
This script is the core engine for generating Ahead-Of-Time (AOT) C++ ZK circuits.
It parses the Intermediate Representation (IR) `graph.json` exported by the 
PyTorch frontend and utilizes the mapping and templates from `backend_cpp_templates.py` 
to generate highly optimized, flattened C++ source files for the MPC/ZK backend.

Dependencies:
    Requires `backend_cpp_templates.py` to be present in the same directory.

Arguments:
    --json       : (Required) Path to the `graph.json` file generated by the exporter.
    --model_name : (Optional) The base name for the generated C++ classes and files. 
                   Defaults to 'GeneratedModel'. (e.g., 'ResNet50', 'VGG16')
    --out_dir    : (Optional) Destination directory path for the generated C++ files.
                   Defaults to './generated_cpp'.

Usage Examples:

    Scenario 1: Basic compilation with default settings
        python compiler.py --json ../extracted_model_data/my_model_20260306/graph.json

    Scenario 2: Specify a custom model name and output directory
        python compiler.py \
            --json /path/to/graph.json \
            --model_name ResNet50 \
            --out_dir ../emp-mvzk/local_models/resnet50_auto

Outputs:
    The compiler will generate three files in the specified `--out_dir`:
    1. <model_name>.h       : Contains data structures for Host (offline) and ZK (online) weights.
    2. <model_name>.cpp     : Contains the I/O loading, ZK injection logic, and the flattened forward pass.
    3. <model_name>_test.cpp: The execution entry point with built-in profiling and OpenMP support.

Integration Note:
    After generation, add the newly created .cpp files to your C++ backend's `CMakeLists.txt`
    and build the executable.
================================================================================
"""

import json
import argparse
from pathlib import Path

# Import the configuration and templates from our decoupled module
from backend_cpp_templates import CPP_API_MAP, TEMPLATE_HEADER, TEMPLATE_CPP, TEMPLATE_TEST


def format_shape(shape_list):
    """ Converts [64, 3, 3, 3] to '{64, 3, 3, 3}' for C++ vectors. """
    return "{" + ", ".join(map(str, shape_list)) + "}"

def get_arg(val, default=0):
    """ Safely extracts scalar arg (like stride/padding) which might be a list. """
    if val is None: return default
    if isinstance(val, (list, tuple)): return val[0]
    return val

def generate_cpp_code(graph_data, model_name):
    host_fields, poly_fields = [], []
    load_stmts, inject_stmts, forward_stmts = [], [], []
    
    input_name = "image"
    output_name = "out"
    
    tab = "    "
    
    # [新增] Scale 追踪器：记录每个张量的当前缩放阶数
    scale_map = {}
    
    for node in graph_data:
        n_name = node["name"]
        n_type = node["type"]
        c_var = f"tensor_{n_name}" # C++ variable name
        
        # 1. Capture Input/Output
        if n_type == "input":
            input_name = c_var
            scale_map[c_var] = 1 # [新增] 输入的 Scale 永远是 1S
            continue
        if n_type == "output":
            # Assuming output node receives exactly one variable from the graph
            output_name = f"tensor_{node['inputs'][0]}"
            continue
            
        # 2. Extract Weights and Generate Loaders
        if "weight_shape" in node:
            w_shape = format_shape(node["weight_shape"])
            host_fields.append(f"{tab}std::vector<uint64_t> {n_name}_w;")
            poly_fields.append(f"{tab}PolyTensor {n_name}_w;")
            
            # Use load_raw_data_from_bin (as designed in tensor_loader.h)
            load_stmts.append(f"{tab}hw.{n_name}_w = load_raw_data_from_bin(party, {w_shape}, bin_dir + \"/{n_name}_weight.bin\");")
            inject_stmts.append(f"{tab}pw.{n_name}_w = exec->input({w_shape}, hw.{n_name}_w);")
            
            # Handle bias dynamically (some layers might be bias=False)
            if "bias_shape" in node:
                b_shape = format_shape(node["bias_shape"])
                host_fields.append(f"{tab}std::vector<uint64_t> {n_name}_b;")
                poly_fields.append(f"{tab}PolyTensor {n_name}_b;")
                
                # [核心修改] 智能判别：只有 conv2d 和 linear 需要双倍 Scale
                needs_double_scale = (n_type in ["conv2d", "linear"])
                is_bias_str = "true" if needs_double_scale else "false"
                
                # 在加载函数中传入 TensorDataType::FP32 以及 is_bias_str
                load_stmts.append(f"{tab}hw.{n_name}_b = load_raw_data_from_bin(party, {b_shape}, bin_dir + \"/{n_name}_bias.bin\", TensorDataType::FP32, {is_bias_str});")
                inject_stmts.append(f"{tab}pw.{n_name}_b = exec->input({b_shape}, hw.{n_name}_b);")
            else:
                inject_stmts.append(f"{tab}pw.{n_name}_b = PolyTensor();")
                
        # 3. Generate Forward Pass Code via Operator Registry
        in_vars = [f"tensor_{i}" for i in node.get("inputs", [])]
        in_var = in_vars[0] if len(in_vars) > 0 else ""
        in_var_0 = in_vars[0] if len(in_vars) > 0 else ""
        in_var_1 = in_vars[1] if len(in_vars) > 1 else ""
        
        # --- [新增] Scale Tracking & Auto-Alignment Logic ---
        out_scale = 1
        
        if n_type in ["conv2d", "linear"]:
            out_scale = scale_map.get(in_var_0, 1) + 1
        elif n_type == "relu":
            out_scale = 1 # 截断阀门，压回 1S
        elif n_type in ["max_pool2d", "avgpool2d", "global_avg_pool2d", "flatten"]:
            out_scale = scale_map.get(in_var_0, 1) # 直接继承上一层的 Scale
        elif n_type == "func_add":
            s0 = scale_map.get(in_var_0, 1)
            s1 = scale_map.get(in_var_1, 1)
            
            # 动态插入对齐代码
            if s0 < s1:
                forward_stmts.append(f"{tab}// [Auto-Align] Scaling up {in_var_0} from {s0}S to {s1}S")
                forward_stmts.append(f"{tab}PolyTensor {in_var_0}_scaled = {in_var_0} * real2fp(1.0);")
                in_var_0 = f"{in_var_0}_scaled"
                if in_var == in_vars[0]: in_var = in_var_0 
                out_scale = s1
            elif s1 < s0:
                forward_stmts.append(f"{tab}// [Auto-Align] Scaling up {in_var_1} from {s1}S to {s0}S")
                forward_stmts.append(f"{tab}PolyTensor {in_var_1}_scaled = {in_var_1} * real2fp(1.0);")
                in_var_1 = f"{in_var_1}_scaled"
                if in_var == in_vars[1]: in_var = in_var_1 
                out_scale = s0
            else:
                out_scale = s0
                
        scale_map[c_var] = out_scale
        # ----------------------------------------------------
        
        stride = get_arg(node.get("stride"), 1)
        padding = get_arg(node.get("padding"), 0)
        k_size = get_arg(node.get("kernel_size"), 3)
        
        # Look up the C++ API template
        if n_type not in CPP_API_MAP or n_type == "unknown":
            raise NotImplementedError(
                f"\n\033[1;31m[COMPILER ERROR] Unsupported Operation Detected: '{n_type}', Node name: '{n_name}').\n"
                f"Please check backend_cpp_templates.py to confirm whether the operation has been implemented.\033[0m"
            )
        template = CPP_API_MAP[n_type]
        
        # Format the C++ string
        cpp_line = template.format(
            out_var=c_var,
            in_var=in_var,
            in_var_0=in_var_0,  # [重要修改] 这里必须使用可能被替换成 _scaled 的安全变量
            in_var_1=in_var_1,  # [重要修改] 同上
            node_name=n_name,
            stride=stride,
            padding=padding,
            kernel_size=k_size,
            node_type=n_type
        )
        
        forward_stmts.append(f"{tab}{cpp_line}")

    return {
        "host_fields": "\n".join(host_fields),
        "poly_fields": "\n".join(poly_fields),
        "load_statements": "\n".join(load_stmts),
        "inject_statements": "\n".join(inject_stmts),
        "forward_statements": "\n".join(forward_stmts),
        "input_name": input_name,
        "output_name": output_name,
        "final_scale_power": scale_map.get(output_name, 2) # [新增] 输出 Scale 阶数
    }

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="ZK C++ Circuit Compiler Engine")
    parser.add_argument("--json", type=str, required=True, help="Path to graph.json")
    parser.add_argument("--model_name", type=str, default="GeneratedModel", help="Name of the generated model class")
    # 把默认值设为 None，这样我们在后面可以动态推导
    parser.add_argument("--out_dir", type=str, default=None, help="Output directory (defaults to the directory containing graph.json)")
    args = parser.parse_args()

    json_path = Path(args.json).resolve() # 获取绝对路径，更加安全
    
    # 核心修改：如果不指定 out_dir，就直接把 C++ 文件生成在 json 所在的文件夹里！
    if args.out_dir is None:
        out_dir = json_path.parent
    else:
        out_dir = Path(args.out_dir).resolve()
        
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\033[1;36m[Compiler]\033[0m Parsing {json_path.name} and metadata ...")
    with open(json_path, 'r') as f:
        graph_data = json.load(f)

    # [状态管理] 读取 SSOT 元数据
    meta_path = json_path.parent / "metadata.json"
    if meta_path.exists():
        with open(meta_path, 'r') as f:
            meta = json.load(f)
    else:
        print("\033[33m[WARNING] metadata.json not found, using default dimensions (1, 3, 32, 32).\033[0m")
        meta = {"N": 1, "C": 3, "H": 32, "W": 32}

    code_sections = generate_cpp_code(graph_data, args.model_name)
    
    # 将元数据尺寸注入到 C++ 模板中
    code_sections.update({
        "model_name": args.model_name,
        "model_name_lower": args.model_name.lower(),
        "N": meta["N"],
        "C": meta["C"],
        "H": meta["H"],
        "W": meta["W"]
    })

    # Fill templates
    h_code = TEMPLATE_HEADER.format(**code_sections)
    cpp_code = TEMPLATE_CPP.format(**code_sections)
    test_code = TEMPLATE_TEST.format(**code_sections)

    # Write to disk
    h_file = out_dir / f"{args.model_name}.h"
    cpp_file = out_dir / f"{args.model_name}.cpp"
    test_file = out_dir / f"{args.model_name}_test.cpp"

    with open(h_file, 'w') as f: f.write(h_code)
    with open(cpp_file, 'w') as f: f.write(cpp_code)
    with open(test_file, 'w') as f: f.write(test_code)

    print("\n\033[32m[SUCCESS] ZK Circuit Compilation Complete!\033[0m")
    print(f"Generated files in: {out_dir.resolve()}")
    print(f"  - {h_file.name}")
    print(f"  - {cpp_file.name}")
    print(f"  - {test_file.name}")